version: '3.7'

services:
    my-registry:
        image: registry
        volumes:
            - registry:/var/lib/registry
        ports:
            - "55000:5000"
        restart: unless-stopped

volumes:
    registry:

